export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_BOARD = 'SET_BOARD'

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST'
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED'
