export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_BOARD = 'SET_BOARD'

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST'
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED'

export const GET_STATS_REQUEST = 'GET_STATS_REQUEST'
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS'
export const GET_STATS_FAILED = 'GET_STATS_FAILED'
