version: '3.8'
services:
  mucahid-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - ./.env.development
    stdin_open: true
    tty: true
