import React from 'react'
import type {NextComponentType} from 'next'
import Head from 'next/head'
import {Navbar, Footer} from '@/layout/index'
import * as S from './style'

const MainLayout: NextComponentType = ({children}) => {
  return (
    <S.MainLayout>
      <Head>
        <title>Mucahids Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <S.MainLayoutContent>{children}</S.MainLayoutContent>
      <Footer />
    </S.MainLayout>
  )
}

export default MainLayout
