import React from 'react'
import PropTypes from 'prop-types'
import type {NextComponentType} from 'next'
import Head from 'next/head'
import {SubscribeBanner} from '@/components/index'
import {Navbar, Footer} from '@/layout/index'
import * as S from './style'

interface IMainLayout {
  children: React.ReactNode
}

const MainLayout: NextComponentType<IMainLayout> = ({children}) => {
  return (
    <S.MainLayout>
      <Head>
        <title>Mucahids Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <S.MainLayoutContent>{children}</S.MainLayoutContent>
      <SubscribeBanner />
      <Footer />
    </S.MainLayout>
  )
}

MainLayout.propTypes = {
  children: PropTypes.node.isRequired,
}

MainLayout.defaultProps = {}

export default MainLayout
