export const district = {
  ADALAR: { value: 1103, label: 'ADALAR' },
  ATAŞEHİR: { value: 2049, label: 'ATAŞEHİR' },
  BEYKOZ: { value: 1185, label: 'BEYKOZ' },
  ÇEKMEKÖY: { value: 2052, label: 'ÇEKMEKÖY' },
  KADIKÖY: { value: 1421, label: 'KADIKÖY' },
  KARTAL: { value: 1449, label: 'KARTAL' },
  MALTEPE: { value: 2012, label: 'MALTEPE' },
  PENDİK: { value: 1835, label: 'PENDİK' },
  SANCAKTEPE: { value: 2054, label: 'SANCAKTEPE' },
  SULTANBEYLİ: { value: 2014, label: 'SULTANBEYLİ' },
  ŞİLE: { value: 1659, label: 'ŞİLE' },
  TUZLA: { value: 2015, label: 'TUZLA' },
  ÜMRANİYE: { value: 1852, label: 'ÜMRANİYE' },
  ÜSKÜDAR: { value: 1708, label: 'ÜSKÜDAR' },
}
