export const POLYCLINIC = {
  106: 'Aile Hekimliği',
  109: 'Anesteziyoloji ve Reanimasyon',
  112: 'Beyin ve Sinir Cerrahisi',
  116: 'Çocuk Cerrahisi',
  117: 'Çocuk Diş Hekimliği',
  118: 'Çocuk Endokrinolojisi',
  119: 'Çocuk Enfeksiyon Hastalıkları',
  120: 'Çocuk Gastroenterolojisi',
  199: 'Çocuk Göğüs Hastalıkları',
  123: 'Çocuk Hematolojisi ve Onkolojisi',
  124: 'Çocuk İmmünolojisi ve Alerji Hastalıkları',
  126: 'Çocuk Kardiyolojisi',
  128: 'Çocuk Nefrolojisi',
  129: 'Çocuk Nörolojisi',
  131: 'Çocuk Romatolojisi',
  132: 'Çocuk Sağlığı ve Hastalıkları',
  133: 'Çocuk Ürolojisi',
  134: 'Çocuk ve Ergen Ruh Sağlığı ve Hastalıkları',
  136: 'Deri ve Zührevi Hastalıkları (Cildiye)',
  198: 'Diş Hekimliği (Genel Diş)',
  138: 'Endodonti',
  139: 'Endokrinoloji ve Metabolizma Hastalıkları',
  140: 'Enfeksiyon Hastalıkları ve Klinik Mikrobiyoloji',
  142: 'Fiziksel Tıp ve Rehabilitasyon',
  144: 'Gastroenteroloji',
  147: 'Genel Cerrahi',
  148: 'Geriatri',
  149: 'Göğüs Cerrahisi',
  150: 'Göğüs Hastalıkları',
  9000001: 'Glokom',
  155: 'Hematoloji',
  157: 'İç Hastalıkları (Dahiliye)',
  158: 'İmmünoloji ve Alerji Hastalıkları',
  161: 'Kadın Hastalıkları ve Doğum',
  162: 'Kalp ve Damar Cerrahisi',
  163: 'Kardiyoloji',
  165: 'Kulak Burun Boğaz Hastalıkları',
  166: 'Nefroloji',
  168: 'Nöroloji',
  170: 'Ortodonti',
  171: 'Ortopedi ve Travmatoloji',
  174: 'Periodontoloji',
  175: 'Plastik, Rekonstrüktif ve Estetik Cerrahi',
  176: 'Protetik Diş Tedavisi',
  177: 'Radyasyon Onkolojisi',
  179: 'Restoratif Diş Tedavisi',
  180: 'Romatoloji',
  181: 'Ruh Sağlığı ve Hastalıkları (Psikiyatri)',
  210: 'Sağlık Kurulu',
  211: 'Sağlık Kurulu ÇÖZGER (Çocuk Özel Gereksinim Raporu)',
  150001: 'Sigarayı Bıraktırma Kliniği',
  189: 'Tıbbi Genetik',
  192: 'Tıbbi Onkoloji',
  168001: 'Uyku Polikliniği',
  196: 'Üroloji',
  103: 'Ağız, Diş ve Çene Cerrahisi',
  104: 'Ağız, Diş ve Çene Radyolojisi',
} as Record<string, string>