export const SAVE_AUTH = 'SAVE_AUTH'

export const SET_NEWSLETTER_REQUEST = 'SET_NEWSLETTER_REQUEST'
export const SET_NEWSLETTER_SUCCESS = 'SET_NEWSLETTER_SUCCESS'
export const SET_NEWSLETTER_FAILED = 'SET_NEWSLETTER_FAILED'

export const GET_USER_METAMASKS_REQUEST = 'GET_USER_METAMASKS_REQUEST'
export const GET_USER_METAMASKS_SUCCESS = 'GET_USER_METAMASKS_SUCCESS'
export const GET_USER_METAMASKS_FAILED = 'GET_USER_METAMASKS_FAILED'
