export const SAVE_AUTH = 'SAVE_AUTH'

export const SET_NEWSLETTER_REQUEST = 'SET_NEWSLETTER_REQUEST'
export const SET_NEWSLETTER_SUCCESS = 'SET_NEWSLETTER_SUCCESS'
export const SET_NEWSLETTER_FAILED = 'SET_NEWSLETTER_FAILED'
