export const CONNECT_BLOCKCHAIN_REQUEST = 'CONNECT_BLOCKCHAIN_REQUEST'
export const CONNECT_BLOCKCHAIN_SUCCESS = 'CONNECT_BLOCKCHAIN_SUCCESS'
export const CONNECT_BLOCKCHAIN_FAILED = 'CONNECT_BLOCKCHAIN_FAILED'

export const CONNECTION_REQUEST = 'CONNECTION_REQUEST'
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS'
export const CONNECTION_FAILED = 'CONNECTION_FAILED'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

export const CHECK_DATA_REQUEST = 'CHECK_DATA_REQUEST'
export const CHECK_DATA_SUCCESS = 'CHECK_DATA_SUCCESS'
export const CHECK_DATA_FAILED = 'CHECK_DATA_FAILED'

export const GET_ALL_MESSAGES_REQUEST = 'GET_ALL_MESSAGES_REQUEST'
export const GET_ALL_MESSAGES_SUCCESS = 'GET_ALL_MESSAGES_SUCCESS'
export const GET_ALL_MESSAGES_FAILED = 'GET_ALL_MESSAGES_FAILED'
