export const CONNECT_BLOCKCHAIN_REQUEST = 'CONNECT_BLOCKCHAIN_REQUEST'
export const CONNECT_BLOCKCHAIN_SUCCESS = 'CONNECT_BLOCKCHAIN_SUCCESS'
export const CONNECT_BLOCKCHAIN_FAILED = 'CONNECT_BLOCKCHAIN_FAILED'
